// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.demo.io.service.grpc.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.io.service.grpc.proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string real_name = 2;</code>
   */
  String getRealName();
  /**
   * <code>string real_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
