// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.demo.io.service.grpc.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_io_service_grpc_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_io_service_grpc_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_io_service_grpc_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_io_service_grpc_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_io_service_grpc_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_io_service_grpc_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_io_service_grpc_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_io_service_grpc_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_io_service_grpc_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_io_service_grpc_proto_StudentResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ngrpc.proto\022\036com.demo.io.service.grpc.p" +
      "roto\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\037\n\nM" +
      "yResponse\022\021\n\treal_name\030\002 \001(\t\"\035\n\016StudentR" +
      "equest\022\013\n\003age\030\001 \001(\005\":\n\017StudentResponse\022\014" +
      "\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"" +
      "_\n\023StudentResponseList\022H\n\017studentRespons" +
      "e\030\001 \003(\0132/.com.demo.io.service.grpc.proto" +
      ".StudentResponse2\200\003\n\016StudentService\022p\n\025G" +
      "etRealNameByUsername\022).com.demo.io.servi" +
      "ce.grpc.proto.MyRequest\032*.com.demo.io.se" +
      "rvice.grpc.proto.MyResponse\"\000\022v\n\017GetStud" +
      "entByAge\022..com.demo.io.service.grpc.prot" +
      "o.StudentRequest\032/.com.demo.io.service.g" +
      "rpc.proto.StudentResponse\"\0000\001\022\203\001\n\030GetStu" +
      "dentsWrapperByAges\022..com.demo.io.service" +
      ".grpc.proto.StudentRequest\0323.com.demo.io" +
      ".service.grpc.proto.StudentResponseList\"" +
      "\000(\001B0\n\036com.demo.io.service.grpc.protoB\014S" +
      "tudentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_demo_io_service_grpc_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_io_service_grpc_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_io_service_grpc_proto_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_demo_io_service_grpc_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_demo_io_service_grpc_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_io_service_grpc_proto_MyResponse_descriptor,
        new String[] { "RealName", });
    internal_static_com_demo_io_service_grpc_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_demo_io_service_grpc_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_io_service_grpc_proto_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_demo_io_service_grpc_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_demo_io_service_grpc_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_io_service_grpc_proto_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_demo_io_service_grpc_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_demo_io_service_grpc_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_io_service_grpc_proto_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
