// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.demo.io.service.grpc.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_io_service_grpc_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_io_service_grpc_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_io_service_grpc_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_io_service_grpc_proto_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngrpc.proto\022\036com.demo.io.service.grpc.p" +
      "roto\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\037\n\nM" +
      "yResponse\022\021\n\treal_name\030\002 \001(\t2\202\001\n\016Student" +
      "Service\022p\n\025GetRealNameByUsername\022).com.d" +
      "emo.io.service.grpc.proto.MyRequest\032*.co" +
      "m.demo.io.service.grpc.proto.MyResponse\"" +
      "\000B0\n\036com.demo.io.service.grpc.protoB\014Stu" +
      "dentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_demo_io_service_grpc_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_io_service_grpc_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_io_service_grpc_proto_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_demo_io_service_grpc_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_demo_io_service_grpc_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_io_service_grpc_proto_MyResponse_descriptor,
        new java.lang.String[] { "RealName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
