// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.demo.io.service.grpc.proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.io.service.grpc.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
